/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador_FRM_VentanaBiblioteca;

/**
 *
 * @author Usuario
 */
public class PanelInformacionLibro extends javax.swing.JPanel {
    Controlador_FRM_VentanaBiblioteca controlador;

    /**
     * Creates new form PanelInformacionLibro
     */
    public PanelInformacionLibro() {
        initComponents();
        
    }
    
     public void agregarEventos(Controlador_FRM_VentanaBiblioteca controlador)
    {
        this.controlador=controlador;
    }
    public String devolverNumeroPrestamo()
    {
        return this.txtNumeroPrestamo.getText();
    }
    
    public void inicializarGUI()
    {
        this.txtNumeroPrestamo.setEnabled(true);
        this.txtNombreUsuario.setEnabled(false);
        this.txtCedulaUsuario.setEnabled(false);
        this.txtISBLibro.setEnabled(false);
        
    }
    
    public void habilitarEdicion()
    {
        this.txtNumeroPrestamo.setEnabled(false);
        this.txtNombreUsuario.setEnabled(true);
        this.txtCedulaUsuario.setEnabled(true);
        this.txtISBLibro.setEnabled(true);
    
    }
    
    public void limpiarGUI()
    {
        this.txtNumeroPrestamo.setText("");
        this.txtNombreUsuario.setText("");
        this.txtCedulaUsuario.setText("");
        this.txtISBLibro.setText("");
    
    }
    
    public void mostrarInformacion(String arreglo[])
    {
        this.txtNombreUsuario.setText(arreglo[1]);
        this.txtCedulaUsuario.setText(arreglo[2]);
        this.txtISBLibro.setText(arreglo[3]);

    }
    
     public String [] devolverInformacion()
    {
        String info[]= new String[4];
        info[0]=this.txtNumeroPrestamo.getText();
        info[1]=this.txtNombreUsuario.getText();
        info[2]=this.txtCedulaUsuario.getText();
        info[3]=this.txtISBLibro.getText();
        
        return info;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNumeroPrestamo = new javax.swing.JTextField();
        txtNombreUsuario = new javax.swing.JTextField();
        txtCedulaUsuario = new javax.swing.JTextField();
        txtISBLibro = new javax.swing.JTextField();

        jLabel1.setText("Número del Préstamo");

        jLabel2.setText("Nombre del Usuario");

        jLabel3.setText("Cédula del Usuario");

        jLabel4.setText("ISB del libro");

        txtNumeroPrestamo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumeroPrestamoKeyPressed(evt);
            }
        });

        txtNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtISBLibro))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCedulaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtNombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                .addComponent(txtNumeroPrestamo)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNumeroPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCedulaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtISBLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreUsuarioActionPerformed

    private void txtNumeroPrestamoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroPrestamoKeyPressed
        if(evt.getKeyCode()==10)
        {
            this.controlador.buscar();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroPrestamoKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtCedulaUsuario;
    private javax.swing.JTextField txtISBLibro;
    private javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JTextField txtNumeroPrestamo;
    // End of variables declaration//GEN-END:variables
}
